site_name: Exploration Toolkit
site_url: https://mydomain.org/mysite
theme:
  name: material

  logo: images/icons/ET_Icon.png
  favicon: images/icons/ET_Icon.png

  font:
    text: Inter

  palette:
    scheme: slate
    #scheme: default

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.indexes
    #- navigation.tabs
    #- navigation.tabs.sticky
    #- navigation.path
    - navigation.sections
    #- navigation.expand
    - search.suggest
    - content.code.copy

plugins:
  - search
  #- redirects:
  #    redirect_maps:
  #      'index.md': 'welcome.md'
  - print-site:
      print_page_title: 'Exploration Toolkit'
      add_table_of_contents: true
      toc_depth: 6

markdown_extensions:
  - pymdownx.blocks.caption
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:  
  - stylesheets/extra.css

nav:
  - Exploration Toolkit:
    - Welcome: welcome.md
    #- Quick Setup: quick-setup.md
    - Setup:
      - setup/index.md
      - Importing: setup/importing.md
      - Scene Setup: setup/scene-setup.md
      - Demos: setup/demos.md
      #- HDRP Setup: setup/hdrp-setup.md
  - Systems:
    - Player:
      - player/index.md
      - Player Controller: player/player-controller.md
      - Input Manager: player/input-manager.md
      - Crosshairs: player/crosshairs.md
      - Custom Player Controller: player/custom-player-controller.md
      - Player Stats: player/player-stats.md
    - Interaction:
      - interaction/index.md
      - Basic Setup: interaction/basic-setup.md
      - Pickup Objects: interaction/pickup-objects.md
      - Inspect Objects: interaction/inspect-objects.md
    - Mechanisms:
      - mechanisms/index.md
      - Doors: mechanisms/doors.md
      - Levers: mechanisms/levers.md
      - Buttons: mechanisms/buttons.md
    - Locks & Unlocking:
      - locks-lockpicking/index.md
      - Lockpicking: locks-lockpicking/lockpicking.md
      - Keypads: locks-lockpicking/keypads.md
      - Combination Locks: locks-lockpicking/combination-locks.md
      #- Keycards: locks-lockpicking/keycards.md
      - Unlockables: locks-lockpicking/unlockables.md
    - Inventory & Items:
      - inventory-items/index.md
      - Items: inventory-items/items.md
      - Inventory Controller: inventory-items/inventory-controller.md
      - Hotbar Inventory: inventory-items/hotbar-inventory.md
      - Window Inventory: inventory-items/window-inventory.md
    - Navigation:
      - navigation/index.md
      - Navigation Markers: navigation/navigation-markers.md
      - World Markers: navigation/world-markers.md
      - Compass Bar: navigation/compass-bar.md
      - Minimap: navigation/minimap.md
    - Camera:
      - camera/index.md
      - Camera Focusing: camera/camera-focusing.md
      - Camera Zoom: camera/camera-zoom.md
    - UI:
      - ui/index.md
      - Menu: ui/menu.md
      - UI Manager: ui/ui-manager.md
      #- Pause Screen: ui/pause-screen.md
  - Resources:
    - Advanced:
      - scripting/index.md
      - ETSystemRegistry: scripting/etsystemregistry.md
      - ETGameSettings: scripting/etgamesettings.md
      - Global Audio Source: scripting/global-audio-source.md
      - Custom Inspectors: scripting/custom-inspectors.md
      #- Script Execution Order: scripting/script-execution-order.md
      - Libraries: scripting/libraries.md
    - Help:
      - help/index.md
      - Changelog: help/changelog.md
      - FAQ: help/faq.md
      - Roadmap: help/roadmap.md
    - Links:
      - links/index.md
      - Play the Demo: https://daniel-buckley.itch.io/exploration-toolkit
      - YouTube Tutorials: https://www.youtube.com/playlist?list=PL7QZMl1mSodk7QgdeduMBVBzTE5YeZBIA
      - Asset Store: https://assetstore.unity.com/packages/slug/336992